### ISSUE TITLE
Front page: text block text aligne is default to right

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#14]
![screen shot 2016-01-22 at 16 40 03](https://cloud.githubusercontent.com/assets/13623224/12513519/dc191594-c126-11e5-847c-cb25c93245c8.png)

**Comment by kaspar-naaber** [comment]
This is a footer's content area and it has to be aligned to left by default. Front page doesn't have it's own content area (it only displays blog articles). However it seems to be an issue on it's own because user might not have a blog on his/her site at all and then the front page layout becomes unusable. User can always switch it to "common page" but maybe we should still add an optional content area? @runnel – please advise.

**Comment by kaspar-naaber** [comment]
Added optional content area to front page.
