### ISSUE TITLE
Gallery: gallery spacing stays too large on smaller screens

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#43]
On smaller screen spacing between photos stays too large. In desktop sizes it ok.
![screen shot 2016-01-29 at 11 17 52](https://cloud.githubusercontent.com/assets/13623224/12671695/2077e50a-c67a-11e5-9134-9a38619f5788.png)

**Comment by kaspar-naaber** [comment]
You are probably using "grid" type gallery with specific "spacing"? In that case it's not the template's issue.

![screenshot 2016-02-10 17 09 13](https://cloud.githubusercontent.com/assets/3191867/12951136/85123954-d019-11e5-921a-de967fe9df1e.png)

Technically it is not an issue at all because the number inserted into "spacing" input is in pixels and the pixel size is not changing when reducing the screen size. But in actual use case it might look a bit weird and should be discussed with @pulges
