### ISSUE TITLE
Blog: if blog post title is long, then it goes out of container (small screen)

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#51]
If blog post don't have photo and blog post title is long, then title goes out of container

![screen shot 2016-03-10 at 11 53 21](https://cloud.githubusercontent.com/assets/13623224/13665858/1c7d2c46-e6b7-11e5-9b4d-35edb8d9995b.png)

**Comment by SSirjes** [comment]
Also in edit mode text "Drag a new picture here from the files panel" is very close to box bordes. Maybe bit padding? Tested iPod
![screen shot 2016-03-10 at 12 01 38](https://cloud.githubusercontent.com/assets/13623224/13666063/3e641e90-e6b8-11e5-8780-f1affc23a6fb.png)

**Comment by kaspar-naaber** [comment]
The problem occurs because the image box maintains 1:1 aspect ratio (is always a square) while the content in it doesn't shrink.

Possible solutions:
1. Hide overflowing text.
![screenshot 2016-03-11 09 47 00](https://cloud.githubusercontent.com/assets/3191867/13696317/42429b02-e76e-11e5-98c3-b72686ff884b.png)

2. Truncate title in the box at N-th letter:
![screenshot 2016-03-11 09 54 48](https://cloud.githubusercontent.com/assets/3191867/13696492/5f07a0f6-e76f-11e5-8329-ec9ff7f0385a.png)

3. There's also a 'hacky' method to hide the overflowing text and add ellipsis at the end which preserves the full title in the HTML, but visually hides it at the point where it overflows. But as I mentioned it is a 'hacky' method and pretty complicated. The full title is under the box anyway so truncating the text from certain amount of characters might be a better solution.

4. Any other suggestions, @runnel ?

**Comment by runnel** [comment]
2 is good :)

**Comment by SSirjes** [comment]
iPhone: article title goes out of container
![screen shot 2016-03-15 at 09 39 24](https://cloud.githubusercontent.com/assets/13623224/13770778/25176432-ea92-11e5-8a9d-729681178561.png)
