### ISSUE TITLE
Creating new "Blog and news", first blog will be duplicated

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#86]
If I create new blog block, then first blog content will be duplicated and in main menu I have 2 same blog content + new blog
1. Is it necessary, that same blog content will be duplicated? It's bit confusing. 
I think it's enough when creating second blog, then first blog stays same and will be not duplicated

2. If my first blog has first tags under submenu (dropdown), then creating second blog they will disappear

Video, what happens if I create new Blog and news layout: http://recordit.co/julMRTpZqt

**Comment by kaspar-naaber** [comment]
As I mentioned, the first blog actually becomes "latest articles" section which includes articles from both – the old and the new blog you just created.

Actually the first "Blogi" page was already the "latest articles" view but if user has only one blog then there's no point to display the actual blog page in the menu because it looks the same as the "latest articles" page ("latest articles" only has latest articles from one blog).

The situation that you created is more misleading because you have renamed the "Home" page to "Blogi" so they have identical names and it looks like it generates a duplicate from the first page.

We will add a one-time notification for to explain the user about this magic behaviour in near future.
